### ISSUE TITLE
tides

### ISSUE THREAD

**Issue by oeon** [SLUGIS/intelreport#19]
can we find a better graphic/information on tides?

**Comment by tstan** [comment]
do you mean in the links section or do you want another graphic on tides in the actual page? 

How's this 
<a href>http://www.centralcoastweather.net/RegionalTides.asp</a>

**Comment by oeon** [comment]
another graphic was the initial thought.

centralcoastweather is okay. This http://www.surfline.com/surf-report/morro-bay-central-california_4193/ was recommended, too.

Not sure if we'll be able to just grab an image/graphic or have to scrape. If it's going to be messy - then we'll just add to the links section.

This would be used for Ocean Rescue incidents, so responders can potentially reference the state of the tides.

**Comment by tstan** [comment]
I've been researching how to nab this information from surfline and it turns out it's actually a paid service and thus the attributes of the infographics are under security. 
<a href>http://www.surfline.com/premiumlanding/index.cfm?pg=regional_forecast_dashboard</a>

since the data from surfline is not text based it is also not possible to scrape so I will just add a link and maybe add the chart from centralcoastweather?

**Comment by oeon** [comment]
:+1: @tstan thanks for the research

**Comment by tstan** [comment]
Surfline added music and some ad popups so unfortunately we cannot use their direct interface with an iframe. Just added their site as a link instead.
