### ISSUE TITLE
Staffing paterns 

### ISSUE THREAD

**Issue by Chief-Tritip** [SLUGIS/intelreport#25]
The staffing patterns section is not updating since we implemented the new backup form.. 
7/4/2015 - Still an issue

**Comment by oeon** [comment]
I think this working now, not sure how it was fixed however. Might take 5 min to update?

**Comment by oeon** [comment]
@tstan @thsteven13 when we resolve this...we need to either document with code-comments or on this wiki page (already established) https://github.com/SLUGIS/intelreport/wiki/Staffing-Patterns ...in more detail, what the code is doing. Specifically, on lines 64, 80, 110 of the AdminReport googleScript, a sheet I.D. is entered...we need to comment exactly what sheet. Perhaps ping @bsyu1125 or @kaysabelle if uncertain.

From what I'm seeing in the Backup:
- the 1st reference to a sheet I.D. is for the AdminReport
- 2nd is for the StaffingPatternREVISED
- 3rd is for the AdminReport again

Why is it interacting with StaffingPatternREVISED (a separate file/sheet) if we are entering the Staffing Pattern information into a worksheet on the AdminReport sheet?

Essentially how we got here- @Chief-Tritip and I were messing with the AdminReport sheet (yes, I know, dangerous...but bosses gonna boss) and we broke it. But this is exactly why we made a backup! Upon reverting to the backup, things didn't reconnect like we anticipated.

**Comment by kaysabelle** [comment]
A little bit of insight that might help:

Each sheet requires triggers to run. You can check them by going to Script Center > Resources > Current Project's Triggers.

Looking at the AdminReportCorrupt script, I see that there are 2 triggers:
1. record(), which runs every 5 minutes
2. onEdit(), which runs every time the spreadsheet is edited

When I checked this morning, the AdminReport sheet did not currently have any triggers, so I added the above two triggers just now. Hopefully this will resolve some of the updating issues. If not, I can investigate again tomorrow morning.

@oeon you're right about the sheets that correspond to the IDs. I think StaffingPatternREVISED may be keeping a record of each time a staffing pattern is crossed out, so we can have a history of them, I'm not sure... but @bsyu1125 would have more insight towards the functionality of StaffingPatternREVISED.

**Comment by oeon** [comment]
awesome @kaysabelle thank you! Perhaps when we reverted from the backup, we did not setup the triggers. I was very careful to not change the ID's in the googleScript from the backup, until it didn't work...but I didn't think about the triggers.

**Comment by oeon** [comment]
> the AdminReport sheet did not currently have any triggers, so I added the above two triggers just now

When I go to Script Center in AdminReport right now, I don't see `Resources`..only an entry for `Read Data`. Is there some terminology confusion perhaps? Functions VS Triggers? One can go Tools > Script Editor > Resources > Current Project's triggers. But if I do that for AdminReport right now..it still says _No triggers set up._ So I'm confused that you said you added two triggers but I don't see it.

With that said: the Intel Report is functioning as expected and I think we can close this issue soon. But I'd like to better understand exactly how we fixed this, include better comments in the AdminReport googleScript and be prepared to fix this whole-setup again, if it gets broken. @thsteven13 If you could work on those three aforementioned tasks and close this issue once we're good.

**Comment by thsteven13** [comment]
@kaysabelle Where did you add the new triggers for record() and onedit() to fix it?

**Comment by kaysabelle** [comment]
@oeon  Sorry about the confusion, I meant this:
1. First open the AdminReport spreadsheet.
2. Click Tools > Script Editor. Navigate to the Script Editor.
3. In the Script Editor, click Resources > Current project's triggers.

@oeon  @thsteven13 **I'm pretty sure that you guys can't see the triggers I added because kaysabelle@gmail.com specifically set the triggers and there's no way for someone else who is NOT kaysabelle@gmail.com to see all the triggers that were set by that account.** The Intel Report scripts should still function correctly because my account has set up the triggers so they are working even if you can't see them. 

Google Scripts doesn't have very good script trigger controls... there's only a way to view all the triggers that [the signed-in account viewing the document] specifically set for the document. There's also a way to view all the triggers across all the sheets that [the signed-in account viewing the document] has set up, but it doesn't show which sheet each trigger corresponds with.

I've re-added the triggers under slugis3400@gmail.com so you can all see them/edit them. I'm disabling the triggers that I set up under kaysabelle@gmail.com to remove redundancies.

**Comment by thsteven13** [comment]
@kaysabelle, Thanks again, Are there any other triggers set up other than on AdminReport and Staffing Patterns? I see extra triggers when listing all triggers, but I don't know where it's from.

**Comment by kaysabelle** [comment]
It doesn't say where the other triggers are from, I just know that they're from other Google Sheets with Google Scripts that are accessible by slugis3400@gmail.com. It might be best not to touch them for now.

**Comment by thsteven13** [comment]
I'm going to close this now. If the intel report should break again, I would be able to fix it.
